import blurbob from "./blurblob.svg"
import charts from "./charts.jpg"
import desk from "./desk.jpg"
import DArrow from "./diagonal-arrow.svg"
import funding from "./funding.png"
import huddle from "./huddle.jpg"
import integrity from "./integrity.png"
import leaf from "./leaf.jpg"
import logoblob from "./logoblob.svg"
import masks from "./masks.jpg"
import pawapay from "./pawapay.png"
import professionalism from "./professionalism.png"
import quality from "./quality.png"
import rainbow from "./rainbow.svg"
import silhouette from "./silhouette.jpg"
import street from "./streets.jpg"
import stripe from "./stripe.png"
import transparency from "./transparency.png"
import vision from "./vision.png"
import logo from "./whitebglogo.png"

export { DArrow, blurbob, charts, desk, funding, huddle, integrity, leaf, logo, logoblob, masks, pawapay, professionalism, quality, rainbow, silhouette, street, stripe, transparency, vision }

